#include <curses.h>
#include "culori.h"

void initializeazaCulori(void)
{
	init_pair(COL_GRANITA, COLOR_BLACK, COLOR_BLACK);
	init_pair(COL_FUNDAL, COLOR_RED, COLOR_WHITE);
	init_pair(COL_NECUCERIT, COLOR_BLACK, COLOR_WHITE);
	init_pair(COL_J1, COLOR_BLACK, COLOR_BLUE);
	init_pair(COL_J2, COLOR_BLACK, COLOR_YELLOW);
	init_pair(COL_J3, COLOR_BLACK, COLOR_RED);
	init_pair(COL_STATUS, COLOR_GREEN, COLOR_BLACK);
	init_pair(COL_MESAJ_SERVER, COLOR_BLACK, COLOR_GREEN);
	init_pair(COL_FUNDAL_INTREBARE, COLOR_GREEN, COLOR_BLACK);
	init_pair(COL_INTREBARE, COLOR_BLACK, COLOR_GREEN);
	init_pair(COL_RASPUNS, COLOR_BLACK, COLOR_YELLOW);
}
